title: Content Guide – after a death 

email: chris.brew@finance.nsw.gov.au
description: >- # this means to ignore newlines until "baseurl:"
  Principles and guidance
baseurl: "/ljdeathstyleguide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

browserTitle: Content style guide for after a death service 

stage: alpha

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
